apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-lab
  labels:
    app: pipeline-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-lab
  template:
    metadata:
      labels:
        app: pipeline-lab
    spec:
      containers:
      - name: pipeline-lab
        image: pipeline-lab:v1.0
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "kubernetes"
        - name: APP_VERSION
          value: "1.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"